Factor out meshopt into its own class
BabylonJS/Babylon.js pull request #10830
Opened 2021-08-07 00:46 UTC by bghgary

Also allow relative paths in draco and meshopt configuration.

Fixes #10822

2021-08-07 09:04 UTC, Popov72 approved these changes

2021-08-07 09:04 UTC, Popov72 commented on localDev/index.html
> +                    url: GetAbsoluteUrl("../dist/preview%20release/meshopt_decoder.js")
Missing the `decoder` parent

2021-08-07 09:04 UTC, Popov72 commented on sandbox/public/index-local.html
> +                    url: GetAbsoluteUrl("../../dist/preview%20release/meshopt_decoder.js")
Missing the `decoder` parent

2021-08-09 11:58 UTC, RaananW requested changes
Setting to request changes until comments are resolved

2021-08-09 16:39 UTC, RaananW commented
You commited all of the dist folder as well. Was that intentional?

2021-08-09 16:51 UTC, bghgary commented
Nope

2021-08-09 19:10 UTC, RaananW approved these changes

2021-08-09 19:13 UTC, merged