Fix spherical harmonics solid angle computation
BabylonJS/Babylon.js pull request #11884
Opened 2022-01-31 18:22 UTC by Meakk

2022-01-31 18:41 UTC, sebavan requested changes
Just a couple nits but it looks good to me !!!

2022-01-31 18:41 UTC, sebavan commented on src/Misc/HighDynamicRange/cubemapToSphericalPolynomial.ts
> +        var AreaElement = (x : number, y : number) => { return Math.atan2(x * y, Math.sqrt(x * x + y * y + 1)); };
Would be great to move this into its own private function to prevent over allocation and garbage despite not being called frequently ?

2022-01-31 18:41 UTC, sebavan commented on src/Misc/HighDynamicRange/cubemapToSphericalPolynomial.ts
> +                    var deltaSolidAngle = AreaElement(u - 0.5 * du, v - 0.5 * dv) - AreaElement(u - 0.5 * du, v + 0.5 * dv) - AreaElement(u + 0.5 * du, v - 0.5 * dv) + AreaElement(u + 0.5 * du, v + 0
could we extract u-0.5du and such to reuse the result as they appear several times in here ?

2022-02-01 10:03 UTC, Popov72 commented on src/Misc/HighDynamicRange/cubemapToSphericalPolynomial.ts
> +    private static AreaElement(x : number, y : number): number {
nit: should be _AreaElement because the function is private

2022-02-01 17:27 UTC, merged