Gltf materials
BabylonJS/Babylon.js pull request #12149
Opened 2022-03-11 20:01 UTC by sebavan

Add a way to either only download the gltf materials or to skip all of them.

2022-03-11 20:06 UTC, deltakosh approved these changes

2022-03-11 22:55 UTC, bghgary approved these changes
A couple of nits. I'm a bit concerned we are adding more and more options without doing to work to make setting options easier, but it should be okay for now.

2022-03-11 22:55 UTC, bghgary commented on loaders/src/glTF/glTFFileLoader.ts
> +     * If true, load only all the materials defined in the file. Defaults to false.
```suggestion
     * If true, load only the materials defined in the file. Defaults to false.
```

2022-03-11 22:55 UTC, bghgary commented on loaders/src/glTF/glTFFileLoader.ts
> +     public skipMaterials = false;
```suggestion
    public skipMaterials = false;
```

2022-03-14 15:38 UTC, bghgary requested changes

2022-03-14 15:38 UTC, bghgary commented on loaders/src/glTF/glTFFileLoader.ts
> +    public customMaterialLoad: Nullable<(material: GLTF2.IMaterial) => Nullable<Material>> = null;
This is the same as adding a glTF loader extension?

2022-03-14 18:03 UTC, merged