add vertexAttribIPointer support Int Data Type
BabylonJS/Babylon.js pull request #12823
Opened 2022-08-02 02:26 UTC by GoodLuckIce

add createVertexBuffer support  Int  Data Type

2022-08-02 14:56 UTC, sebavan commented
This does not compile as you need to put vertexAttribIPointer definition in this file https://github.com/sebavan/Babylon.js/blob/master/packages/dev/core/src/LibDeclarations/webgl2.d.ts#L1

2022-08-02 15:19 UTC, deltakosh approved these changes

2022-08-03 14:40 UTC, RaananW requested changes
Please run the formatter after you are done with the changes (or follow the same formatting as the rest of the code)

2022-08-03 15:23 UTC, sebavan commented on packages/dev/core/src/Engines/thinEngine.ts
> +                this._gl.vertexAttribIPointer(indx, size, type, stride, offset);
The definition should be added intohttps://github.com/sebavan/Babylon.js/blob/master/packages/dev/core/src/LibDeclarations/webgl2.d.ts#L1 as we do for the rest of webgl2 specific functions instead.

2022-08-03 17:49 UTC, sebavan commented
closed for https://github.com/BabylonJS/Babylon.js/pull/12830 so I can merge for the next release

2022-08-03 17:49 UTC, closed without merging