Allow Texture static create functions (not Parse) to take Engine
BabylonJS/Babylon.js pull request #13221
Opened 2022-11-08 19:01 UTC by Palmer-JC

2022-11-08 19:41 UTC, sebavan commented on packages/dev/core/src/Materials/Textures/cubeTexture.ts
> +        if (sceneOrEngine instanceof Scene) {
As you can not import the Scene Value, I would advise to only check for (sceneOrEngine as Scene).useDelayedTextureLoading !== "undefined)

2022-11-08 19:42 UTC, sebavan commented on packages/dev/core/src/Materials/Textures/cubeTexture.ts
> +        if (sceneOrEngine instanceof Scene) {
Instead of doing the check back, you could store the result of the test in a variable

2022-11-09 15:01 UTC, Popov72 requested changes

2022-11-09 17:08 UTC, Popov72 commented
`_IsScene` is private to `BaseTexture`, that's why you can't access it. Actually, it is simply doing `return sceneOrEngine.getClassName() === "Scene"`, that's why I suggested to use the same test.

2022-11-09 18:11 UTC, sebavan commented
If you follow sceneOrEngine.getClassName() === "Scene" you won t need to remove the type at the top :-)

2022-11-09 19:07 UTC, Popov72 commented
What do you mean?

It seems testing `sceneOrEngine.getClassName() === "Scene"` will work with `import type { Scene } from "../../scene";`

2022-11-09 19:41 UTC, sebavan commented
Yup, exactly that :-) no need to do this change https://github.com/BabylonJS/Babylon.js/pull/13221/files#diff-03f2af9a6752fe469eb572ec0afa30d2ff5ae943f0a1e1c59020cc54bd7c1264R4

2022-11-10 17:17 UTC, Palmer-JC commented
Am a little lost here, but something is working right off the current CDN.babylon.js.  I thought I had switched the framework to the one I had made, but I am only using the resulting D.TS in the transpile.  Yet it runs.

After that, I double checked (right from the console this time), and engine is in the call (and the call that calls it).
```javascript
(function (XR_UI) {
    class Environment {
        static Get(engine) {
            if (!Environment._Cube) {
                Environment._Cube = BABYLON.CubeTexture.CreateFromPrefilteredData(Environment._Url, engine, '.env');
                Environment._Cube.name = null;
                Environment._Url = null;
            }
            return Environment._Cube;
        }
    }
    Environment._Url = 'data:application/...
```

So, is the only thing needed is the D.TS file????

2022-11-10 18:53 UTC, sebavan commented
It is expected as you basically only changed typings in the PR and preventing setting useDelayedTextureLoading and In JS setting a field prevently undefined would basically do not break. The only thing is engine would have a property useDelayedTextureLoading :-)

2022-11-11 18:09 UTC, Palmer-JC commented
I finally got the whole picture, in that "I don't need no stinking CreateFromPrefilteredData()".  It is only just a 4 line static function of which in my case, I only need one, the public constructor.

I just added the constructor in the little class with the embedded data, and I am done.  Sorry for your trouble.

2022-11-11 18:09 UTC, closed without merging