Cache loaded dom images on Image class so the playground-editor doesn't have to reload them often
BabylonJS/Babylon.js pull request #13388
Opened 2022-12-28 17:40 UTC by carolhmj

Without the change:
![ge-no-cache](https://user-images.githubusercontent.com/6002144/209851133-13453ef9-8178-423f-9721-4dd7bbd53ca0.gif)
With the change:
![ge-cache](https://user-images.githubusercontent.com/6002144/209851145-ac34937f-d94b-4ca1-af94-dc758257f1a8.gif)

2022-12-31 13:09 UTC, RaananW reviewed
Is the data being disposed when the GUI is disposed?

2023-01-02 17:15 UTC, sebavan requested changes
I am not sure this should be part of the Image class, could the cache be moved in the editor as it looks dedicated for it ?

2023-01-03 14:16 UTC, carolhmj commented
> I am not sure this should be part of the Image class, could the cache be moved in the editor as it looks dedicated for it ?

@sebavan this behavior isn't totally exclusive to the editor, as this would happen in any case where the control is repeatedly cleared and added to the parent. For example, this Playground: https://playground.babylonjs.com/#F2SG3A#2

Behaves like this now:
![image-movement-gui-current](https://user-images.githubusercontent.com/6002144/210374725-70b936af-46fb-45c7-a834-9a1fa7a1f063.gif)

But with the cache:
![image-movement-gui-new](https://user-images.githubusercontent.com/6002144/210374756-ffb99f9b-05f1-407f-b232-551d02cad5ff.gif)

2023-01-03 16:02 UTC, RaananW commented
My only comment is caching to a static object without clearing it when the image/scene/engine disposes. Not sure what would be the best dispose mechanism here, but it should be cleared for sure when the engine is disposed (otherwise it is technically a memory leak). Is it possible to dispose the data when an image is disposed?

2023-01-03 17:32 UTC, kircher1 commented
@carolhmj, would this also remove the duplicated image requests for grass.png in this playground? https://playground.babylonjs.com/#XCPP9Y#16922

2023-01-03 19:37 UTC, carolhmj commented
> @carolhmj, would this also remove the duplicated image requests for grass.png in this playground? https://playground.babylonjs.com/#XCPP9Y#16922

@kircher1 I tested and it does remove the duplication! I'm just going to move this to be a ADT level cache so it doesn't leak memory :)

2023-01-04 18:02 UTC, carolhmj commented
Cache was moved to the ADT! @RaananW @sebavan @kircher1 

The only caveat is that, since we need to know to which ADT the image belongs to cache it, caching will only occur if `img.source` is set AFTER it is added to a control.

2023-01-04 18:19 UTC, bjsplat commented
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13388/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

2023-01-04 21:17 UTC, sebavan approved these changes

2023-01-04 23:59 UTC, sebavan commented
> The only caveat is that, since we need to know to which ADT the image belongs to cache it, caching will only occur if `img.source` is set AFTER it is added to a control.

ohhh yeah right, I wonder how often we actually set it after knowing it is a ctor parameter ?

2023-01-05 13:59 UTC, RaananW commented on packages/dev/gui/src/2D/controls/image.ts
> +                this._onImageLoaded();
Isn't this called twice in case of cache? Sorry if it isn't, might be the formatting of the changes.

2023-01-05 14:50 UTC, RaananW approved these changes
LGTM. @sebavan - i'll let you merge it after your concerns are addressed.

2023-01-10 20:10 UTC, carolhmj commented
@sebavan @RaananW updated to have the cache back as a static Image member, but we keep track of how many times that image is being used to clear it when it's not necessary anymore

2023-01-10 20:31 UTC, sebavan approved these changes

2023-01-10 20:34 UTC, RaananW approved these changes

2023-01-10 21:01 UTC, merged