Add support for unsigned int uniform
BabylonJS/Babylon.js pull request #13433
Opened 2023-01-13 11:09 UTC by newbeea

Current version can not pass unsigned int uniform to shader when using ShaderMaterial
[Example](https://playground.babylonjs.com/#1OH09K#1727)
This PR add support for passing unsigned int uniform

2023-01-13 11:10 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-01-13 11:15 UTC, newbeea commented
Hi @carolhmj thank you for your help,
this is my solution for：[How can i pass uint uniform](https://forum.babylonjs.com/t/how-can-i-pass-uint-uniform/37321/5)

2023-01-13 11:24 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-01-13 11:45 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/13433/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13433/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13433/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13433/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13433/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13433/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13433/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13433/merge#BCU1XR#0

2023-01-13 15:14 UTC, Popov72 requested changes
Only a couple of comments, good job!

2023-01-13 18:29 UTC, sebavan commented on packages/dev/core/src/Engines/Native/nativePipelineContext.ts
> +        if (this._engine.setUInt(this._uniforms[uniformName]!, value)) {
@bghgary, @CedricGuillemet, I guess we d need to support those in native now :-)

2023-01-16 02:09 UTC, newbeea commented on packages/dev/core/src/Materials/uniformBuffer.ts
> +
thanks for your review, I noticed the 'Uint32Array' bug, but i am not sure, so i didn't change that ... 
I will fix that

2023-01-16 03:14 UTC, bjsplat commented
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13433/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

2023-01-16 04:00 UTC, newbeea commented
> 



> Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at
> 
> https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13433/merge/testResults/webgl1/index.html
> 
> If tests were successful afterwards, this report might not be available anymore.

"Iridescence NME" and "Light Projection Texture" failed randomly in visualization tests of webgl1 or webgl2

2023-01-16 19:28 UTC, Popov72 approved these changes
LGTM!

2023-01-16 20:38 UTC, sebavan approved these changes

2023-01-17 14:36 UTC, merged