Allows colour changes from bboxrenderer observers
BabylonJS/Babylon.js pull request #13956
Opened 2023-06-13 14:33 UTC by aaloksg

Uses the this.frontColor and this.backColor properties directly when drawing the bounding boxes to allow colour changes from onBeforeBoxRenderingObservable observers.

2023-06-13 14:35 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-06-13 15:04 UTC, RaananW approved these changes

2023-06-13 16:24 UTC, sebavan requested changes

2023-06-13 16:24 UTC, sebavan commented on packages/dev/core/src/Rendering/boundingBoxRenderer.ts
> +            this._uniformBufferFront.updateDirectColor4("color", this.frontColor.toColor4());
you should replace with: updateColor4(this.frontColor, 1); cause at the moment you are introducing a perf regression by creating a color 4 on each iteration.

2023-06-14 06:09 UTC, aaloksg commented on packages/dev/core/src/Rendering/boundingBoxRenderer.ts
> +                this._uniformBufferBack.updateDirectColor4("color", this.backColor.toColor4());
Yes makes sense, thanks! I've done so.

2023-06-14 09:29 UTC, Popov72 approved these changes

2023-06-14 15:50 UTC, sebavan approved these changes

2023-06-14 15:50 UTC, merged