Optimized mesh.subdivide function by delaying the BB refresh to once …
BabylonJS/Babylon.js pull request #13999
Opened 2023-06-23 09:22 UTC by JonathanIcon

Optimized mesh.subdivide function by delaying the BB refresh to once the subdivision is finished. 
Previously, copying entire mesh data inside the loop made the algorithm time scale with the number of subdivisions. 
This is no longer the case. 100+ times faster on a multi-million vertex mesh.

2023-06-23 09:23 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-06-23 09:41 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/13999/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13999/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13999/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13999/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13999/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13999/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13999/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13999/merge#BCU1XR#0

2023-06-23 11:32 UTC, Popov72 approved these changes
Thanks!

2023-06-23 13:07 UTC, JonathanIcon commented
What's wrong with the CI ?

2023-06-23 19:49 UTC, sebavan approved these changes
Nice !!!

2023-06-23 19:59 UTC, sebavan requested changes

2023-06-23 19:59 UTC, sebavan commented on packages/dev/core/src/Meshes/mesh.ts
> +        this.refreshBoundingInfo();
@JonathanIcon Can you move this up one line ? I am afraid synchronizeInstances will populate back bounding info on all instances.

2023-06-23 21:02 UTC, JonathanIcon commented
SureEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : sebavan ***@***.***> Date : 23/06/2023  22:00  (GMT+01:00) À : "BabylonJS/Babylon.js" ***@***.***> Cc : JonathanIcon ***@***.***>, Mention ***@***.***> Objet : Re: [BabylonJS/Babylon.js] Optimized mesh.subdivide function by delaying the BB refresh to once … (PR #13999) 
@sebavan requested changes on this pull request.



In packages/dev/core/src/Meshes/mesh.ts:
>  
             offset += subdivisionSize;
         }
 
         this.synchronizeInstances();
+        this.refreshBoundingInfo();

@JonathanIcon Can you move this up one line ? I am afraid synchronizeInstances will populate back bounding info on all instances.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-06-26 11:45 UTC, RaananW approved these changes

2023-06-26 14:28 UTC, sebavan approved these changes

2023-06-26 14:28 UTC, merged