add Env to NME Preview
BabylonJS/Babylon.js pull request #14398
Opened 2023-10-06 05:34 UTC by onekit-boss

We can custom Env, Image and toggle Env / Background color now.

2023-10-06 05:36 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-10-06 05:48 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/14398/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14398/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14398/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14398/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14398/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14398/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14398/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14398/merge#BCU1XR#0

2023-10-09 10:21 UTC, Popov72 reviewed
Just to be sure we are ok with the GUI, here's how it appears:
![image](https://github.com/BabylonJS/Babylon.js/assets/4152247/542bccdb-32e0-4a67-b956-f585112d9ace)

cc @PatrickRyanMS

2023-10-09 10:24 UTC, onekit-boss commented on packages/tools/nodeEditor/src/components/preview/previewAreaComponent.tsx
> +                                title="Turn on/off background"
ok. I will rename it

2023-10-09 15:42 UTC, sebavan commented
LGTM if @PatrickRyanMS is all good with it :-)

2023-10-09 16:12 UTC, deltakosh approved these changes

2023-10-09 19:55 UTC, sebavan commented
Also one last thought for @RaananW to be sure importing .env would not break any kindz of buildzzzz 🐝🐝🐝🐝🐝

2023-10-10 13:40 UTC, RaananW commented
> Also one last thought for @RaananW to be sure importing .env would not break any kindz of buildzzzz 🐝🐝🐝🐝🐝

Works fine, as this is just a static file in the public directory.
Might cause an issue when used as a package, as you will need to deliver the file yourself.

2023-10-10 15:43 UTC, sebavan requested changes
Nice thanks a lot !!! a last change and I can merge it in :-) Could you make "https://assets.babylonjs.com/environments/environmentSpecular.env" a public static so that users can point it at their own URL if need be :-)

2023-10-10 15:53 UTC, onekit-boss commented
> > Nice thanks a lot !!! a last change and I can merge it in :-) Could you make "https://assets.babylonjs.com/environments/environmentSpecular.env" a public static so that users can point it at their own URL if need be :-)
> 
> yes. Now it is a exists URL of babylon assets (https://assets.babylonjs.com), not a file .

I use this URL as other source codes of babylon.js .your can find the URL in bellow files:
packages\dev\core\src\Helpers\environmentHelper.ts
packages\tools\sandbox\src\tools\environmentTools.ts

2023-10-10 15:58 UTC, sebavan commented
yes but in environmentHelper users can override it here https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Helpers/environmentHelper.ts#L344 and sandbox is not meant to be used as a framework. 

Users needs to be able to control where they download assets from.

2023-10-10 16:06 UTC, onekit-boss commented
> yes but in environmentHelper users can override it here https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Helpers/environmentHelper.ts#L344 and sandbox is not meant to be used as a framework.
> 
> Users needs to be able to control where they download assets from.

your mean is. ........"user need custom a env of the NME Preview window?" . I has add a "upload button" on the right of "model ComboBox" in NME Preview window. so user can override the default env "https://assets.babylonjs.com/environments/environmentSpecular.env".

2023-10-10 16:09 UTC, sebavan commented
Oh no, sorry, I just mean if you move it in a static public field or a let in the module so a developer consuming the npm package can change it before loading nme.

2023-10-10 16:10 UTC, onekit-boss commented
> a public static

or...... your mean is a public static  filed  of the class?

2023-10-10 16:12 UTC, sebavan commented
something like this:

```
public static DefaultEnvironmentURL = "https://assets.babylonjs.com/environments/environmentSpecular.env"';

private _refreshPreviewMesh(force?: boolean) {
        switch (this._globalState.envType) {
            case PreviewType.Room:
                this._hdrTexture = new CubeTexture(DefaultEnvironmentURL , this._scene);
                if (this._hdrTexture) {
                    this._prepareBackgroundHDR();
                }
                break;
            case PreviewType.Custom: {
                const blob = new Blob([this._globalState.envFile], { type: "octet/stream" });
                const reader = new FileReader();
                reader.onload = (evt) => {
                    const dataurl = evt.target!.result as string;
                    this._hdrTexture = new CubeTexture(dataurl, this._scene, undefined, false, undefined, undefined, undefined, undefined, undefined, ".env");
                    this._prepareBackgroundHDR();
                };
                reader.readAsDataURL(blob);
                break;
            }
        }
```

2023-10-10 16:14 UTC, onekit-boss commented
> something like this:
> 
> ```
> public static DefaultEnvironmentURL = "https://assets.babylonjs.com/environments/environmentSpecular.env"';
> 
> private _refreshPreviewMesh(force?: boolean) {
>         switch (this._globalState.envType) {
>             case PreviewType.Room:
>                 this._hdrTexture = new CubeTexture(DefaultEnvironmentURL , this._scene);
>                 if (this._hdrTexture) {
>                     this._prepareBackgroundHDR();
>                 }
>                 break;
>             case PreviewType.Custom: {
>                 const blob = new Blob([this._globalState.envFile], { type: "octet/stream" });
>                 const reader = new FileReader();
>                 reader.onload = (evt) => {
>                     const dataurl = evt.target!.result as string;
>                     this._hdrTexture = new CubeTexture(dataurl, this._scene, undefined, false, undefined, undefined, undefined, undefined, undefined, ".env");
>                     this._prepareBackgroundHDR();
>                 };
>                 reader.readAsDataURL(blob);
>                 break;
>             }
>         }
> ```

thanks. I got it :)

2023-10-10 16:18 UTC, sebavan approved these changes

2023-10-10 16:59 UTC, merged

2023-10-10 16:59 UTC, PatrickRyanMS commented
> Just to be sure we are ok with the GUI, here's how it appears: ![image](https://user-images.githubusercontent.com/4152247/273556968-542bccdb-32e0-4a67-b956-f585112d9ace.png)
> 
> cc @PatrickRyanMS

sorry for the late response, I have been out of the office. The only thing I see is that the icon for environment is a little small in comparison to the rest on the bar. It should be sized to fit with the size of the other icons. If needed, I can provide a new icon, but it would be preferable to use the same svg if possible. Something like this:

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/05e37aa9-ce85-4eed-8b32-95bf8f4d928b)

2023-10-10 18:18 UTC, sebavan commented
@PatrickRyanMS it looks real strange zoomed in like it would be a bold font :-( could you create another svg ? like the other ones in the bar ?

2023-10-10 18:20 UTC, PatrickRyanMS commented
I can make a new svg to fit with the current icons. Give me a few minutes.

2023-10-10 18:37 UTC, PatrickRyanMS commented
@sebavan, here's the updated icon. This is saved at the same size as the rest of the icons, so the css should be the same:
[environment_24_regular.zip](https://github.com/BabylonJS/Babylon.js/files/12860764/environment_24_regular.zip)

![image](https://github.com/BabylonJS/Babylon.js/assets/31326855/2233c0f6-49df-4307-98fe-cc96fd25a675)