Fix incorrect spelling of `wgslLanguageFeatures` (should be `WGSLLanguageFeatures`)
BabylonJS/Babylon.js pull request #14403
Opened 2023-10-07 19:34 UTC by dr-vortex

Bug reproduction:

Install  `@babylonjs/core@6.23.0` and navigate to `node_modules/@babylonjs/core/Engines/engine.d.ts:1272`

Actual:
![image](https://github.com/BabylonJS/Babylon.js/assets/75621402/0a836870-948e-4d60-9049-71332f192fc8)

Error message:
![image](https://github.com/BabylonJS/Babylon.js/assets/75621402/608e3ca1-00f3-4225-ae98-6b2df9531bc4)

Expected:
![image](https://github.com/BabylonJS/Babylon.js/assets/75621402/44565548-2650-4e1d-aba8-3c40d084027b)

The erroneous code is defined in [`packages/dev/core/src/LibDeclarations/webgpu.d.ts:71`](https://github.com/BabylonJS/Babylon.js/blob/6.23.0/packages/dev/core/src/LibDeclarations/webgpu.d.ts#L71)

2023-10-07 19:35 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-10-07 19:37 UTC, dr-vortex commented
@sebavan @Popov72 @RaananW 

If you are available, I think this PR needs to get merged and published ASAP since it is preventing any builds with Typescript.

2023-10-07 19:47 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/14403/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14403/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14403/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14403/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14403/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14403/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14403/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14403/merge#BCU1XR#0

2023-10-08 00:57 UTC, Popov72 requested changes
The name of the property should aslo be changed.

2023-10-08 00:57 UTC, Popov72 commented on packages/dev/core/src/LibDeclarations/webgpu.d.ts
> +    readonly WGSLLanguageFeatures: WGSLLanguageFeatures;
```suggestion
    readonly wgslLanguageFeatures: WGSLLanguageFeatures;
```

2023-10-08 02:05 UTC, Popov72 approved these changes

2023-10-08 02:06 UTC, merged