Fix stack panel giving a warning for children with resizeToFit.
BabylonJS/Babylon.js pull request #14452
Opened 2023-10-23 12:29 UTC by carolhmj

Forum issue: https://forum.babylonjs.com/t/control-is-using-height-in-percentage-mode-inside-a-vertical-stackpanel-warnings-after-update-to-6-25-0/45071

2023-10-23 12:31 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-10-23 12:46 UTC, RaananW requested changes

2023-10-23 12:46 UTC, RaananW commented on packages/dev/gui/src/2D/controls/stackPanel.ts
> +                if (child._height.isPercentage && !child._automaticSize && !(child as any)._resizeToFit) {
nit - can we avoid using any? TextBlock is already imported as type, this should work as is
```suggestion
                if (child._height.isPercentage && !child._automaticSize && !(child as TextBlock)._resizeToFit) {
```

2023-10-23 12:51 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/14452/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14452/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14452/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14452/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14452/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14452/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14452/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14452/merge#BCU1XR#0

2023-10-23 15:41 UTC, RaananW commented on packages/dev/gui/src/2D/controls/stackPanel.ts
> +                if (child._height.isPercentage && !child._automaticSize && !(child as TextBlock)._resizeToFit) {
```suggestion
                if (child._height.isPercentage && !child._automaticSize && !(child as TextBlock).resizeToFit) {
```

2023-10-23 18:00 UTC, bjsplat commented
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14452/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

2023-10-23 18:02 UTC, bjsplat commented
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14452/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

2023-10-23 18:55 UTC, bjsplat commented
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14452/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

2023-10-23 18:55 UTC, bjsplat commented
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14452/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

2023-10-24 10:43 UTC, RaananW approved these changes

2023-10-24 10:57 UTC, merged