ShaderMaterial: Add support for logarithmic depth
BabylonJS/Babylon.js pull request #14581
Opened 2023-12-05 11:04 UTC by Popov72

See https://forum.babylonjs.com/t/log-depth-buffer-makes-overlapping-meshes-edge-disappear/46152

2023-12-05 11:05 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2023-12-05 11:21 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/14581/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14581/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14581/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14581/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14581/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14581/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14581/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14581/merge#BCU1XR#0

2023-12-05 11:56 UTC, RaananW approved these changes
Just one comment regarding logging

2023-12-05 11:56 UTC, RaananW commented on packages/dev/core/src/Materials/shaderMaterial.ts
> +        this._useLogarithmicDepth = value && this.getScene().getEngine().getCaps().fragmentDepthSupported;
if not supported but set to true, we might want to notify the user that it could not be enabled

2023-12-05 16:52 UTC, sebavan requested changes
I think in this case we should add it to nme, background material  as well and most of the one from the material library ?

Is there a convenient way to inject the related shader code ?

2023-12-05 18:01 UTC, Popov72 commented
A convenient way, not really, because you have to call some code in `isReadyForSubMesh` (to inject the #define) and `bindForSubMesh` (to bind the uniform with the right value). So, we would have to update all the classes for which we want to add support for logarithmic depth. It's definitely possible, though.

2023-12-05 19:02 UTC, sebavan commented
yup I am just worried that it will come back as bugs if we move it down without supporting it

2023-12-05 19:39 UTC, deltakosh approved these changes

2023-12-06 14:18 UTC, Popov72 commented
I've updated all the materials!

2023-12-06 15:59 UTC, sebavan approved these changes

2023-12-06 15:59 UTC, merged