Add back convertion to float for Matrix Indices
BabylonJS/Babylon.js pull request #14758
Opened 2024-02-01 18:24 UTC by SergioRZMasson

We believe this change was made by accident. Babylon Native currently needs matrix index buffers to be converted to float in the JS side.

2024-02-01 18:26 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-02-01 18:32 UTC, bghgary requested changes

2024-02-01 18:32 UTC, bghgary commented on packages/dev/loaders/src/glTF/2.0/glTFLoader.ts
> +        if (accessor.sparse) {
This shouldn't be reverted.

```suggestion
        if (accessor.sparse || accessor.bufferView == undefined) {
```

2024-02-01 18:33 UTC, sebavan reviewed
should this be only for native if it incurs any extra conversion cost ?

2024-02-01 18:34 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-02-01 18:48 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/14758/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14758/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14758/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14758/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14758/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14758/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14758/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14758/merge#BCU1XR#0

2024-02-01 19:09 UTC, SergioRZMasson commented
Possibly yes, but our conclusion was that this line was changed by mistake in a previews PR.

2024-02-01 19:14 UTC, sebavan commented
Are you sure it was not for perf ? cc @Popov72 just in case ?

2024-02-01 20:02 UTC, bghgary commented
I made this change accidentally.

2024-02-01 20:11 UTC, Popov72 commented
Matrix indices buffers don't have a type in the glTF file (as other types of vertex buffers have a type)? In that case, I guess we should create the vertex buffer according to this type?

2024-02-01 20:41 UTC, bghgary commented
> Matrix indices buffers don't have a type in the glTF file (as other types of vertex buffers have a type)? In that case, I guess we should create the vertex buffer according to this type?

I'm not sure what you mean by this. What do you mean by type? Maybe the following statement will help? Babylon matrix indices is equivalent to glTF joints.

2024-02-01 20:54 UTC, Popov72 commented
By type, I mean int16, int32, float, etc. Positions, normals, etc don't have to be float in a glTF file, they can have another type. So I guess it's the same thing for the joint indices? Or does the spec mandate a specific type (but float would be a bit strange, I would think that int16/int32 would be more appropriate for joint indices)?

2024-02-05 18:34 UTC, SergioRZMasson commented
> By type, I mean int16, int32, float, etc. Positions, normals, etc don't have to be float in a glTF file, they can have another type. So I guess it's the same thing for the joint indices? Or does the spec mandate a specific type (but float would be a bit strange, I would think that int16/int32 would be more appropriate for joint indices)?

@Popov72 , I think the glTF 2.0 specification states that position, normals, and tangents must be float:

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html

And joint indexes must be unsigned short:

![image](https://github.com/BabylonJS/Babylon.js/assets/97050577/cc2e6506-5ce1-4d18-a129-2af024d5678c)

2024-02-05 22:36 UTC, bghgary commented
> By type, I mean int16, int32, float, etc. Positions, normals, etc don't have to be float in a glTF file, they can have another type. So I guess it's the same thing for the joint indices? Or does the spec mandate a specific type (but float would be a bit strange, I would think that int16/int32 would be more appropriate for joint indices)?

The type conversion to float is just for the shader since [webgl does not support integer attributes](https://stackoverflow.com/questions/27874983/webgl-how-to-use-integer-attributes-in-glsl).

2024-02-06 10:59 UTC, Popov72 commented
WebGL2 supports integer attributes:

https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/vertexAttribIPointer

But I understand it's required because our shaders take a `vec4` for the indices.

2024-02-06 20:04 UTC, Popov72 approved these changes

2024-02-06 20:05 UTC, bghgary approved these changes

2024-02-06 20:05 UTC, merged