Volumetric spotlight
BabylonJS/Babylon.js pull request #15046
Opened 2024-04-29 21:01 UTC by ademola-lou

This PR implements volumetric spotlight

Test: http://localhost:1338/#0BUGL8

2024-04-29 21:02 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-04-29 21:20 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/15046/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15046/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15046/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15046/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15046/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15046/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15046/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15046/merge#BCU1XR#0

2024-04-29 21:24 UTC, bjsplat commented
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15046/merge/testResults/webgl2playwright/index.html

2024-04-29 21:30 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15046/merge/testResults/webgpuplaywright/index.html

2024-05-01 19:21 UTC, ademola-lou commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +export class VolumetricSpotLight extends SpotLight {
i'll fix that

Thanks for the review!

2024-05-05 20:45 UTC, ademola-lou commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +export class VolumetricSpotLight extends SpotLight {
hmm, the direction of the cone is not in sync with the light

2024-05-05 22:24 UTC, ademola-lou commented
Yeah this should also fix the issue with the cone lookAt direction

2024-05-06 10:57 UTC, Popov72 requested changes
I'd like to decouple `SpotLight` from `VolumetricSpotLight` as much as possible (better for class independence and tree shaking).

I don't think it's necessary to modify the `SpotLight` class. The user can simply do `new VolumetricSpotLight(...)` to create a volumetric spotlight. This would also get rid of the `IVolumetricSpotLight` interface.

I'd also like to change the class name, because if we implement a true volumetric light in the future, we'll probably want to use `VolumetricSpotLight` for the name... I'm not sure which name to use (`SimpleVolumetricSpotLight`? `FakeVolumetricSpotLight`?). Let's summon @bghgary, the master of names!

Finally, you need to add documentation to the class/methods to keep the CI happy :)

2024-05-06 10:57 UTC, Popov72 commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +        this.scene.registerBeforeRender(() => {
You should save the returned observer (and use `onBeforeRenderObservable` instead of `registerBeforeRender`) and remove it in a `dispose` method.

2024-05-06 10:57 UTC, Popov72 commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +    }
You can remove half of the code and call `this._update()` instead, as this is duplicated code.

2024-05-06 10:57 UTC, Popov72 commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +    rayLength?: number;
You should make getters/setters for these properties, and recreate the cone mesh when they are updated. Or make these properties protected/private if we don't want the user to change them after creation.

2024-05-06 10:57 UTC, Popov72 commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +              needAlphaTesting: true
I don't think we need to enable alpha testing?

2024-05-06 10:57 UTC, Popov72 commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +              uniforms: ["world", "worldView", "worldViewProjection", "view", "projection" ],
You can remove "uv", "worldView", "view" and "projection", as they are not used in the shaders.

2024-05-06 10:57 UTC, Popov72 commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +        const lightPos = this.spotLight.position.clone();
As this function is called each frame, you should remove all the GC and not create new objects.

Use `TmpVectors.Vector3[0]`, `TmpVectors.Vector3[1]`, etc to hold temporary results.

2024-05-08 22:14 UTC, deltakosh requested changes

2024-05-08 22:14 UTC, deltakosh commented on packages/dev/core/src/Lights/spotLight.ts
> +        console.log("hmm createVolumetricSpotLight");
Needs to remove the console.log

2024-05-08 22:14 UTC, deltakosh commented on packages/dev/core/src/Lights/volumetricSpotLight.ts
> +        const dir = lightPos.subtract(this.spotLight.direction)
same here with subtract to ref

2024-05-10 20:30 UTC, ademola-lou commented
new test PG: http://localhost:1338/#KIXHUK#3

2024-05-10 20:53 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15046/merge/testResults/webgpuplaywright/index.html

2024-05-13 13:44 UTC, sebavan commented on packages/dev/core/src/Lights/simpleVolumetricSpotLight.ts
> +import { Observer, RenderTargetTexture, TmpVectors } from "..";
it is not allowed to import from a folder, import every element from their respective files.

2024-05-13 13:48 UTC, sebavan commented
Marked as draft until the PR is ready. Would be great to have the format/lint/doc and at least one visual test.

Also it would be great to ensure it follows the various falloff types inverse squared vs linear and so on ?

2024-06-03 16:38 UTC, sebavan commented
Let me close for now and I ll let you reopen when ready ?

2024-07-03 17:47 UTC, closed without merging

2025-02-08 08:31 UTC, benkuper commented
Hello, any update on this ?