Update physicsBody.ts to not silently fail when scene is not provided
BabylonJS/Babylon.js pull request #15233
Opened 2024-06-26 18:48 UTC by vtange

It might just be a documentation fix, but if we want to address the silent fail we can also do it. Is there a situation that we want to make PhysicsBody without inputting Scene at the very start? Shapes cannot be attached without Scene.

https://github.com/BabylonJS/Documentation/pull/1156

2024-06-26 18:49 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-06-26 19:02 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/15233/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15233/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15233/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15233/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15233/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15233/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15233/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15233/merge#BCU1XR#0

2024-06-26 19:11 UTC, bjsplat commented
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15233/merge/testResults/webgl2playwright/index.html

2024-06-26 19:12 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15233/merge/testResults/webgpuplaywright/index.html

2024-06-26 22:58 UTC, ryantrem commented
It seems strange for this check to be here at all since the param is of type `Scene` and not `Nullable<Scene>` and we enable `strictNullChecks`. What is the situation where null ends up being passed in? I expect we have many places in the code where we rely on `strictNullChecks` and type checking rather than a runtime check.

2024-06-27 11:39 UTC, RaananW requested changes
This should resolve like other classes do it:

https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/node.ts#L357

2024-06-28 08:04 UTC, CedricGuillemet commented
> This should be resolved like other classes do it:
> 
> https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/node.ts#L357
> 
> A more fundamental question is - why is this code there at all. Scene is a required field, so there should never be a case where scene is undefined. @CedricGuillemet , any input here?

I checked the history log and this non-null scene check was one of the 1st lines written for Physics V2. It passed all the reviews until now :) Anyways, use standard and expected behavior. I would copy/paste line pointed by @RaananW

2024-06-29 03:31 UTC, closed without merging