Port StandardMaterial to webgpu
BabylonJS/Babylon.js pull request #15349
Opened 2024-08-01 17:10 UTC by deltakosh

2024-08-01 17:12 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-08-01 17:23 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/15349/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15349/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15349/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15349/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15349/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15349/merge#BCU1XR#0

2024-08-01 17:31 UTC, bjsplat commented
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/testResults/webgl2playwright/index.html

2024-08-01 18:24 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/testResults/webgpuplaywright/index.html

2024-08-01 20:49 UTC, sebavan requested changes
Once [packages/tools/tests/test/visualization/webgpu_webgpu_log.txt](https://github.com/BabylonJS/Babylon.js/pull/15349/files#diff-1d11bde17281f736c21d06cae2be0d288d0637f0d6e1b3d2da67dd56c4cfdcfc) is removed, all good to be merged :-)

2024-08-01 20:52 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/testResults/webgpuplaywright/index.html

2024-08-01 20:56 UTC, sebavan approved these changes

2024-08-01 21:31 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/testResults/webgpuplaywright/index.html

2024-08-01 22:20 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/testResults/webgpuplaywright/index.html

2024-08-02 15:54 UTC, RaananW commented on packages/dev/core/src/Materials/standardMaterial.ts
> +import { UniformBuffer } from "./uniformBuffer";
leaving a comment to avoid merging for now (need to push some changes)

2024-08-02 18:09 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/testResults/webgpuplaywright/index.html

2024-08-02 18:10 UTC, deltakosh commented
@Popov72 : I ported almost everything but the OIT PG seems to resist: #1PLV5Z#104

I had to move the depth output to be a vec4 and I don't know if this is the cause of the bad rendering

2024-08-02 18:43 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15349/merge/testResults/webgpuplaywright/index.html

2024-08-02 22:04 UTC, deltakosh commented
@Popov72: I found my mistake :D

2024-08-02 22:27 UTC, merged