UniformBuffer: Add setTextureArray to uniform buffers
BabylonJS/Babylon.js pull request #15516
Opened 2024-09-03 15:16 UTC by Popov72

See https://forum.babylonjs.com/t/when-i-enable-the-material-plugin-can-i-pass-cubetextures-into-the-material-as-an-array/53108

2024-09-03 15:18 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-09-03 15:23 UTC, sebavan requested changes
I am not sure texture management should be on UBO as well as it is redundant code only ?

2024-09-03 15:32 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/15516/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15516/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15516/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15516/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15516/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15516/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15516/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15516/merge#BCU1XR#0

2024-09-03 15:33 UTC, deltakosh approved these changes

2024-09-03 15:40 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15516/merge/testResults/webgpuplaywright/index.html

2024-09-03 15:41 UTC, bjsplat commented
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15516/merge/testResults/webgl2playwright/index.html

2024-09-03 20:39 UTC, ryantrem approved these changes

2024-09-03 23:23 UTC, Popov72 commented
> I am not sure texture management should be on UBO as well as it is redundant code only ?

We already had `setTexture`, that's why I added `setTextureArray` (we can't remove `setTexture`, anyway, because of backward compatibility reasons).

2024-09-04 00:30 UTC, sebavan approved these changes

2024-09-04 00:30 UTC, merged