Add plugin for customizing diffuse light color.
BabylonJS/Babylon.js pull request #15511
Opened 2024-09-02 23:43 UTC by kircher1

This is useful for rendering techniques where light color may change dynamically based on the position of the fragment being shaded (e.g. applying sun light to a large terrain)

2024-09-02 23:44 UTC, kircher1 commented
After a successful CI build, I will share a playground that ensures this functionality works as expected.

2024-09-02 23:45 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-09-02 23:55 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/15511/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15511/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15511/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15511/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15511/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15511/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15511/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15511/merge#BCU1XR#0

2024-09-03 00:06 UTC, bjsplat commented
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15511/merge/testResults/webgl2playwright/index.html

2024-09-03 00:56 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15511/merge/testResults/webgpuplaywright/index.html

2024-09-03 07:21 UTC, Popov72 requested changes

2024-09-03 07:21 UTC, Popov72 commented on packages/dev/core/src/ShadersWGSL/ShadersInclude/lightFragment.fx
> +                info.diffuse = computeHemisphericDiffuseLighting(preInfo, diffuse.rgb, light{X}.vLightGround);
`{X}` is missing for all `diffuse` occurrences.

2024-09-03 16:41 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15511/merge/testResults/webgpuplaywright/index.html

2024-09-03 16:55 UTC, Popov72 approved these changes

2024-09-03 17:32 UTC, sebavan approved these changes

2024-09-03 17:44 UTC, merged