GS Volume Culling
BabylonJS/Babylon.js pull request #15705
Opened 2024-10-15 14:47 UTC by CedricGuillemet

This is the 1st step for performance improvements with GS.
AABB Volumes used are coming from Compressed .PLY quantized chunks. It's far for being efficient. But goal here is to have everything in place to try different algorithms while not increasing complexity too much at once.

Batch of 256 splats are culled. visible ones are sorted and that subset is used for instance count.
It should decrease the pressure on GPU/CPU a little.

Next:
- Better partitioning (octree)
- wasm sorting
- radix sort?
- per splat culling
- per volume sorting of splats and volume sorting

2024-10-15 14:48 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-10-15 16:31 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-10-15 16:47 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/15705/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15705/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15705/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15705/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15705/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15705/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15705/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15705/merge#BCU1XR#0

2024-10-15 16:56 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15705/merge/testResults/webgpuplaywright/index.html

2024-10-15 17:30 UTC, Popov72 requested changes

2024-10-15 17:30 UTC, Popov72 commented on packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
> +export interface BoundingVolume {
I think `BoundingVolume` is a bit too generic a name, maybe prefix it with `GaussianSplatting` or something similar?

2024-10-15 17:30 UTC, Popov72 commented on packages/dev/core/src/Meshes/GaussianSplatting/gaussianSplattingMesh.ts
> +            //Logger.Log(`ahahahah ${this._vertexCount} - ${e.data.subsetSize}`);
```suggestion
```

2024-10-15 17:30 UTC, Popov72 commented on packages/dev/loaders/src/SPLAT/splatFileLoader.ts
> +import { GaussianSplattingMesh, type BoundingVolume } from "core/Meshes/GaussianSplatting/gaussianSplattingMesh";
```suggestion
import type { BoundingVolume } from "core/Meshes/GaussianSplatting/gaussianSplattingMesh";
import { GaussianSplattingMesh } from "core/Meshes/GaussianSplatting/gaussianSplattingMesh";
```

2024-10-16 08:43 UTC, CedricGuillemet commented
Switching back to draft, I'm not sure CPU culling on a webworker is a good way to improve perf for high splat count.

2024-11-07 08:34 UTC, closed without merging