Usdz exporter
BabylonJS/Babylon.js pull request #15707
Opened 2024-10-15 20:21 UTC by deltakosh

2024-10-15 20:24 UTC, bjsplat commented
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

2024-10-15 20:40 UTC, bjsplat commented
Snapshot stored with reference name:
refs/pull/15707/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15707/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15707/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15707/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15707/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15707/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15707/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15707/merge#BCU1XR#0

2024-10-15 20:49 UTC, bjsplat commented
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15707/merge/testResults/webgpuplaywright/index.html

2024-10-15 20:51 UTC, bjsplat commented
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15707/merge/testResults/webgl2playwright/index.html

2024-10-16 08:27 UTC, Popov72 requested changes
There's no need to export camera(s)?

2024-10-16 08:27 UTC, Popov72 commented on packages/dev/serializers/src/USDZ/usdzExporter.ts
> +import type { Geometry } from "core/Meshes";
```suggestion
import type { Geometry } from "core/Meshes/geometry";
```

2024-10-16 13:15 UTC, deltakosh commented
There is but in a second pr

2024-10-16 13:36 UTC, Popov72 approved these changes

2024-10-16 13:41 UTC, merged